### PR TITLE
added login button

### PR DESCRIPTION
**Pull request by Dhruvil-Lakhtaria**
Added a login button.

### CODE REVIEW

**Comment by nishant-nayak** [comment]
image

Can you do the following:

- [ ] Update the text on Register button to just **Register**
- [ ] Add some spacing between the Register and Login buttons while ensuring the buttons stay centered in the `landing-text` div

**Comment by Dhruvil-Lakhtaria** [comment]
op1
op2
-[X] Update the text on Register button to just Register
-[X] Add some spacing between the Register and Login buttons while ensuring the buttons stay centered in the landing-text div

**Comment by Dhruvil-Lakhtaria** [comment]
Added option to hide register and login button. I could not import variable from settings.py into views.py so as of now declared it inside views.py only. Have a look ;).

**Comment by nishant-nayak** [comment]
Merged in #22. Thanks for your contribution!

**Pull request closed without merging**
